export const supportedCryptos = [
    { symbol: 'BTC', name: 'Bitcoin', id: 'bitcoin' },
    { symbol: 'ETH', name: 'Ethereum', id: 'ethereum' },
    { symbol: 'USDT', name: 'Tether', id: 'tether' },
    { symbol: 'XRP', name: 'Ripple', id: 'ripple' },
    { symbol: 'BNB', name: 'Binance coin', id: 'binancecoin' },
    { symbol: 'SOL', name: 'Solana', id: 'solana' },
    { symbol: 'DOGE', name: 'Dogecoin', id: 'dogecoin' },
    { symbol: 'VET', name: 'Vechain', id: 'vechain' },
    { symbol: 'WOO', name: 'WOO', id: 'woo' },
    { symbol: 'ADA', name: 'Cardano', id: 'cardano' },
    { symbol: 'LINK', name: 'Chainlink', id: 'chainlink' },
    { symbol: 'SHIB', name: 'Shiba Inu', id: 'shiba-inu' },
    { symbol: 'WIF', name: 'dogwifhat', id: 'dogwifcoin' },
    { symbol: 'SUI', name: 'Sui', id: 'sui' },
    { symbol: 'BCH', name: 'Bitcoin Cash', id: 'bitcoin-cash' },
];