export const icons = [
    { id: "stock", icon: <img width="24" height="24" src="https://img.icons8.com/color/24/stocks.png" alt="stocks" /> },
    { id: "crypto", icon: <img width="24" height="24" src="https://img.icons8.com/color/24/bitcoin--v1.png" alt="bitcoin--v1" /> },
    { id: "precious_metals", icon: <img width="24" height="24" src="https://img.icons8.com/color/24/gold-bars.png" alt="gold-bars" /> },
    { id: "real_estate", icon: <img width="24" height="24" src="https://img.icons8.com/color/24/building.png" alt="building" /> },
    { id: "equity", icon: <img width="24" height="24" src="https://img.icons8.com/color/24/shop.png" alt="shop" /> },
    { id: "cash", icon: <img width="24" height="24" src="https://img.icons8.com/color/24/cash.png" alt="cash" /> },
    { id: "asset-list", icon: <img width="24" height="24" src="https://img.icons8.com/fluency/24/list.png" alt="list" /> },
    { id: "asset-dist", icon: <img width="24" height="24" src="https://img.icons8.com/doodle/24/pie-chart--v1.png" alt="pie-chart--v1" /> },
    { id: "asset-hist", icon: <img width="24" height="24" src="https://img.icons8.com/arcade/24/time.png" alt="time" /> },
    { id: "net-worth", icon: <img width="48" height="48" src="https://img.icons8.com/color/48/average-2.png" alt="average-2" /> },
    { id: "info", icon: <img width="40" height="40" src="https://img.icons8.com/ultraviolet/40/info--v1.png" alt="info--v1" /> },
    { id: "arrow", icon: <img width="48" height="48" src="https://img.icons8.com/pieces/48/arrow.png" alt="arrow" /> },
    { id: "user-icon", icon: <img width="32" height="32" src="https://img.icons8.com/pulsar-color/32/admin-settings-male.png" alt="admin-settings-male" /> },
];